Readme improvements
eclipse-thingweb/node-wot pull request #1043
Opened 2023-07-31 11:30 UTC by egekorkan

Mostly small changes such as:
- NodeJS -> Node.js
- the folder to change after cloning does not have thingweb anymore, i.e. `cd node-wot` instead of `cd thingweb.node-wot`
- English typos and formulation (mostly highlighted by Grammarly)
- Online Thing indentation

2023-07-31 14:51 UTC, relu91 approved these changes
Thanks! LGTM

2023-07-31 16:40 UTC, danielpeintner requested changes
Looks good in general however there are still appearances of "NodeJS" which should be replaced with "Node.js"

2023-07-31 18:11 UTC, egekorkan commented
> Looks good in general however there are still appearances of "NodeJS" which should be replaced with "Node.js"

Done :)

2023-08-01 08:35 UTC, danielpeintner approved these changes

2023-08-01 08:35 UTC, merged