docs: typos in OPCUA readme
eclipse-thingweb/node-wot pull request #1201
Opened 2023-12-19 10:16 UTC by danielpeintner

2023-12-19 10:20 UTC, egekorkan requested changes

2023-12-19 10:20 UTC, egekorkan commented on packages/binding-opcua/README.md
> +some useful applications built on top of thingweb.node-wot and the OPCUA binding.
```suggestion
some useful applications built on top of node-wot and the OPCUA binding.
```

2023-12-20 09:15 UTC, egekorkan approved these changes

2023-12-20 10:17 UTC, relu91 approved these changes

2023-12-20 10:18 UTC, merged