Move to esbuild instead of browserify
eclipse-thingweb/node-wot pull request #1336
Opened 2024-12-02 16:53 UTC by relu91

This PR should eventually completely move us from the old browserify build to a more modern toolchain based on esbuild and web/test-runner. There are still things to fix:
- [ ] Rebase on main
- [ ] Create a new workflow only for browser tests (we don't need the matrix for browser testing)
- [ ] Configure web/test-runner to run on CI with the playwright or similar but use developer browser locally (?).

2024-12-04 18:09 UTC, relu91 commented
I opted out browser tests by removing the `test` script in the browser bundle. So now the CI will only run node tests and in the next commit, I will create a workflow just for browser tests. The only incovient is that now developers should run `npm run test:all` instead of `npm run test`. `test:all` is automatically executed once you push too.

2024-12-05 08:46 UTC, danielpeintner commented
> The only incovient is that now developers should run `npm run test:all` instead of `npm run test`. `test:all` is automatically executed once you push too.

We don't mention the test commands at all (at the moment). Since the CI will run the check, developers will notice problems latest once pushing. Hence, I don't think we _need_ to mention `test:all` (but we can of course).

2024-12-13 11:38 UTC, relu91 commented
Sorry there were complications with prettier (which I've updated to keep the new runner tests in check). I had to also re-run the format command since it seems that the new prettier has different rules. Sorry for making reviewing this harder... please let me know if there something wrong that you spot.

Regarding how the browser tests are run, they can run using `npm run test:browser` but only if the developer really want to test there. The new workflow should be activated once we merge this PR and should guarantee that even if the developer forgets we get always green light from browser too.

2024-12-13 13:19 UTC, danielpeintner requested changes
I didn't spot any obvious issue apart from "master" vs "main".

After fixing that, I am fine with merging...

Thanks a lot @relu91 !!

2024-12-13 13:19 UTC, danielpeintner commented on .github/workflows/browser-test.yml
> +        branches: [main]
```suggestion
        branches: [master]
```

2024-12-13 13:19 UTC, danielpeintner commented on .github/workflows/browser-test.yml
> +        branches: [main]
```suggestion
        branches: [master]
```

2024-12-13 14:13 UTC, relu91 commented
> I didn't spot any obvious issue apart from "master" vs "main".
> 
> After fixing that, I am fine with merging...
> 
> Thanks a lot @relu91 !!

You are right! that's why they didn't run!!! nice catch. pushed the fix.

2024-12-13 14:28 UTC, relu91 commented
Now we hit a bug with optional dependencies: 
> Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828).

This [error](https://github.com/eclipse-thingweb/node-wot/actions/runs/12317389224/job/34379768120?pr=1336#step:6:17) is suggesting to re-generate the `package-lock.json`

2024-12-13 15:53 UTC, danielpeintner approved these changes
I think now everything seems to work 👍

2024-12-13 18:08 UTC, merged